# Generated by Django 5.0 on 2023-12-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('Dest_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Dest_Desc', models.CharField(max_length=255)),
                ('Dest_Img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_Name', models.CharField(blank=True, default='Any', max_length=50, null=True)),
                ('Place_Desc', models.TextField()),
                ('Place_high', models.TextField(default='ALL are High')),
                ('Place_Img', models.ImageField(upload_to='')),
                ('Place_price', models.FloatField()),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.destination')),
            ],
        ),
    ]
