# Generated by Django 5.0 on 2023-12-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
