# Generated by Django 5.0 on 2023-12-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Duration',
            field=models.CharField(default='1/Day & 1N', max_length=6),
        ),
    ]
