# Generated by Django 5.0 on 2023-12-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_place_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='Duration',
        ),
        migrations.AddField(
            model_name='place',
            name='Day',
            field=models.CharField(default='1/Day', max_length=6),
        ),
        migrations.AddField(
            model_name='place',
            name='Night',
            field=models.CharField(default='1/Night', max_length=6),
        ),
    ]
