# Generated by Django 5.0 on 2023-12-15 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_remove_place_duration_place_day_place_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='Night',
            field=models.CharField(default='1/Night', max_length=7),
        ),
        migrations.AlterField(
            model_name='place',
            name='Place_Name',
            field=models.CharField(default='Any', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='sliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImg', models.ImageField(upload_to='')),
                ('sliderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.destination')),
                ('sliderParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.place')),
            ],
        ),
    ]
