# Generated by Django 5.0 on 2023-12-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactModel',
        ),
    ]
