# Generated by Django 5.0 on 2023-12-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_rename_contact_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Subject', models.CharField(max_length=50)),
                ('Content', models.TextField()),
            ],
        ),
    ]
