# Generated by Django 4.1.5 on 2023-12-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUsername', models.CharField(max_length=10)),
                ('userFullName', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=50)),
                ('userContact', models.IntegerField()),
                ('userBirth', models.DateField(auto_now_add=True)),
                ('userAddress', models.TextField()),
            ],
        ),
    ]
